services:
  api:
    container_name: hobi_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=hobiadmin
      - PGHOST=db
      - PGPASSWORD=hobipass
      - PGDATABASE=hobi
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: hobi_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=hobi
      - POSTGRES_USER=hobiadmin
      - POSTGRES_PASSWORD=hobipass
volumes:
  dbdata:
networks: 
  default:
    name: hobi_api